### ISSUE TITLE
变量未定义

### ISSUE THREAD

**Issue by 307545758** [Neeky/mysql-protocol-packets#1]
Traceback (most recent call last):
  File "mysql-login.py", line 339, in <module>
    main(host=args.host, port=args.port, user=args.user, password=args.password)
  File "mysql-login.py", line 308, in main
    if len(auth_data) == 1 and auth_data[0] == 4:
UnboundLocalError: local variable 'auth_data' referenced before assignment

**Comment by 307545758** [comment]
![image](https://user-images.githubusercontent.com/19641571/140453805-783e7149-3d76-4ee2-8eff-895fb2d0a8a2.png)
修改过后卡着没反应了  
2021-11-05 11:27:17,999 - root - MainThread - INFO - 265  - 发起到 10.38.154.3:3306 的 TCP 连接 .
2021-11-05 11:27:18,029 - root - MainThread - INFO - 271  - 收到来自 MySQL-Server 的握手包 .
2021-11-05 11:27:18,029 - root - MainThread - INFO - 276  - 握手包解析完成
2021-11-05 11:27:18,029 - root - MainThread - INFO - 303  - 握手响应包发送完成 .
